baseURL: "https://trunghng.github.io"
title: Littleroot
paginate: 7
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Littleroot
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, hugo-PaperMod]
  author: Trung H. Nguyen
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # auto, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/favicon/favicon.ico"
    favicon16x16: "/images/favicon/favicon-16x16.png"
    favicon32x32: "/images/favicon/favicon-32x32.png"
    apple_touch_icon: "/images/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/images/favicon/android-chrome-512x512.png"

  label:
    text: "Littleroot"
    icon: "/images/others/littleroottown.png"
    iconHeight: 27

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: 'Welcome to my place! 👨‍💻'
    subtitle: This is where I document something I've learned.
    imageUrl: "/images/others/shaymin.jpg"
    imageWidth: 300
    imageHeight: 270
    imageTitle: me & shaymin
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Archive
        url: archives

  # home-info mode
  homeInfoParams:
    Title: "Welcome to my place! 👨‍💻"
    Content: This is where I document something I've learned.

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/trunghng"
    - name: email
      url: "mailto:trung.skipper@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    linkFullImages: true

  editPost:
    URL: # "https://github.com/trunghng/trunghng.github.io/content"
    Text: # "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: post
      name: Posts
      url: /posts/
      weight: 5
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  tableOfContents:
    endLevel: 6
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
